[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS,HEAD"
